site_name: RustBag
site_url: https://balbok0.github.io/rustbag
repo_url: https://github.com/balbok0/rustbag

plugins:
  - search
  - gen-files:
      scripts:
      - .ci/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [crates/python/rustbag]  # search packages in the src folder
          options:
            merge_init_into_class: true
            show_source: false



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: brown
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: material/github


extra:
  version:
    provider: mike