version: '3.7'

# Settings and configurations that are common for all containers
services:
  minio:
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2024-02-26T09-33-48Z
    command: server --console-address ":9001" /data
    volumes:
      - ./example_bags:/data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
