name: Generate [version] documentation

on:
  push:
    tags:
    - '\d+.\d+.\d+'

jobs:
  build_docs:
    name: Generate [version] documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Python dependencies
        run: python3 -m pip install -r ./.ci/docs-requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy with mike 🚀
        run: |
          mike deploy --push ${{ github.ref_name }}
